### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dplewis** [parse-community/parse-php-sdk#401]
@montymxb @flovilmart Here is a small roadmap for this SDK. 

I'll be busy for a while but they are up for grabs.

- [X] [and Query](https://github.com/parse-community/Parse-SDK-JS/pull/367)
- [X] [nor Query](https://github.com/parse-community/parse-server/pull/4768)
- [X] [containedBy Query](https://github.com/parse-community/parse-server/pull/4766)
- [X] [containsStartingWith Query](https://github.com/parse-community/parse-server/pull/3864)
- [X] [sort option for near Queries](https://github.com/parse-community/parse-server/pull/4825)
- [X] [query IncludeAll / include('*')](https://github.com/parse-community/parse-server/pull/4838)
- [ ] [fetch with include](https://github.com/parse-community/Parse-SDK-JS/pull/631)
- [ ] [allow multiple stages aggregate](https://github.com/parse-community/parse-server/pull/4835)

If you have a better way of posting future roadmaps let me know.

**Comment by dplewis** [comment]
@flovilmart I know that have been used in the past. I’ve never personally used them. Are they effective and do you think we can get the community involved.

**Comment by flovilmart** [comment]
I’m not sure, perhaps adding a line on the README, creating a milestone etc may help a bit more :)

**Comment by montymxb** [comment]
I'll get a milestone setup for this 👍 . Thanks for bringing this up @dplewis ! 

Also @flovilmart  sorry for being uninvolved lately...past 5-6 months has been _very_ busy. I still want to get back on board with moving the .NET sdk along and such, whenever I get some time.

**Comment by flovilmart** [comment]
@montymxb no need to be sorry, you owe nothing to no-one :) I've been very busy as well!

**Comment by dplewis** [comment]
@flovilmart I've never used milestones either. They look like a good alternative.

**Comment by dplewis** [comment]
How do you set milestones? Wanted to add sort to `near` queries.

**Comment by dplewis** [comment]
@montymxb Any updates on fixing the tests? No rush or pressure, take your time.

**Comment by montymxb** [comment]
@dplewis I was taking a look at them this morning. Still having issues with getting the test server up, but I believe I should be able to resolve it today. Once that's fixed I'll get the changes integrated here so CI can tell us what needs to be attended to.

**Comment by montymxb** [comment]
#403 rectifies the CI related test issues with a few adjustments. Tests are back on track 👍 .
