### ISSUE TITLE
Publish release

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-php-sdk#492]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-php-sdk/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-php-sdk/issues?q=is%3Aissue).

### Feature / Enhancement Description

A new release should be published. Since it's been a long time since the last release, this issue should help us to gather the knowledge about release publishing for the Parse PHP SDK.

From the Parse PHP docs:
- a) Install via git cloning (so it takes this repo as is, with a given tag)
- b) Install via Composer (https://packagist.org/packages/parse/php-sdk) -> it's unclear at this point how a Parse PHP SDK release is published to composer, or even how that package there is managed.

**Comment by mtrezza** [comment]
So the composer file seems to be for the [packagist](https://packagist.org) registry, which says:

> Once you entered your public repository URL in there, your package will be automatically crawled periodically. You just have to make sure you keep the composer.json file up to date.

So this is publishing automatically. I have requested the ownership transfer from the registry directly, but if @acinader could transfer ownership that could be easier.

**Comment by mtrezza** [comment]
The package has been auto-updated in the packagist registry. Closing this issue, release seems to be have been successful.
